services:
  db:
    image: mariadb:10.11
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - private
    ports:
      - "${DB_PORT}:3306"

  app:
    build: .
    develop:
      watch:
        - action: sync
          path: src/
          target: /app/src/
          ignore:
            - src/__pycache__/
        - action: rebuild
          path: config/requirements.txt
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DISPLAY: host.docker.internal:0
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
networks:
  public:
  private: